F90 = mpifort
INC = /user/hi221/local/fftw-3.3.4/include/
LIB = /user/hi221/local/fftw-3.3.4/lib/

OBJ = typedef.o rbmat.o ffts.o dnsdata.o
#flags =  -ffree-line-length-none -I$(INC) -L$(LIB) -cpp  -g -check all -fpe3 -fpe-all=3 -debug all
flags = -I$(INC) -cpp -L$(LIB)  -Ofast
libs = -lfftw3

channel: $(OBJ) channel.o
	$(F90) $(flags) -o  $@ $(OBJ) channel.o $(libs)
%.o : %.f90
	$(F90) $(flags) -c  $<
clean: 
	rm *.mod *.o

split: $(OBJ) split.o 
	$(F90) $(flags) -o $@ $(OBJ) split.o $(libs)
